baseURL = "https://www.wittrup.xyz"
languageCode = "en-us"
title = "Thoughts by Christian Wittrup"
theme = "SimpleBlogTheme"
copyright ="© 2020, Christian Wittrup"
googleAnalytics = "UA-169820698-2"
paginate = 4

[taxonomies]
  tag = "tags"

[params]
  headertitle = "My Thoughts"

[menu]
  [[menu.main]]
    name = "Frontpage"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


